server:
  port: 8087

management:
  endpoints:
    web:
      exposure:
        include: '*'

dubbo:
  application:
    name: warehouse-service
  registry:
    address: nacos://127.0.0.1:8848
  protocol:
    name: dubbo
    port: 20887
