apiVersion: apps/v1
kind: Deployment
metadata:
  name: pay-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pay-service
  template:
    metadata:
      labels:
        app: pay-service
    spec:
      containers:
        - name: pay-service
          image: <DOCKER_USER>/pay-service:${BUILD_NUMBER}
          ports:
            - containerPort: 8087
---
apiVersion: v1
kind: Service
metadata:
  name: pay-service
spec:
  selector:
    app: pay-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8087
