apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websocket-service
  template:
    metadata:
      labels:
        app: websocket-service
    spec:
      containers:
        - name: websocket-service
          image: <DOCKER_USER>/websocket-service:${BUILD_NUMBER}
          ports:
            - containerPort: 9500
---
apiVersion: v1
kind: Service
metadata:
  name: websocket-service
spec:
  selector:
    app: websocket-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9500
