server:
  port: 8555
  shutdown: graceful # 启用优雅停机

management:
  endpoints:
    web:
      exposure:
        include: '*'

dubbo:
  application:
    name: user-service
    qos-enable: false
  registry:
    address: nacos://10.0.0.253:8848,10.0.0.253:8850,10.0.0.253:8852
    register-mode: instance
  protocol:
    name: dubbo
    port: 28555

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s # 延长停机超时时间