server:
  port: 8555
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus  # 暴露 prometheus 指标
  endpoint:
    prometheus:
      enabled: true  # 显式启用 prometheus endpoint
  prometheus:
    metrics:
      export:
        enabled: true

dubbo:
  application:
    name: user-service
    qos-enable: false
  registry:
    address: nacos://nacos-headless.default.svc.cluster.local:8848
    register-mode: instance
  protocol:
    name: dubbo
    port: 28555