server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: '*'

dubbo:
  application:
    name: address-service
    qos-enable: false
  registry:
    address: nacos://127.0.0.1:8848,127.0.0.1:8850,127.0.0.1:8852
    register-mode: instance
  protocol:
    name: dubbo
    port: 20881

logging:
  level:
    com.alibaba.csp.sentinel: DEBUG




