server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: '*'

dubbo:
  application:
    name: address-service
    qos-enable: false
  registry:
    address: nacos://127.0.0.1:8848
  protocol:
    name: dubbo
    port: 20880

logging:
  level:
    com.alibaba.csp.sentinel: DEBUG




