server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: '*'

dubbo:
  application:
    name: email-service
    qos-enable: false
  registry:
    address: nacos-headless.default.svc.cluster.local:8848
    register-mode: instance
  protocol:
    name: dubbo
    port: 20883
